import pg from "pg";

const connectionString =
  process.env.DATABASE_URL ||
  "postgresql://postgres.rbgohyvmjefowkvnjmha:Gz6dnlh3920064400@aws-1-eu-west-1.pooler.supabase.com:5432/postgres";

const pool = new pg.Pool({
  connectionString,
  ssl: { rejectUnauthorized: false },
});

const newCategories = [
  { id: "hot-drinks", name: "المشروبات الساخنة", icon: "coffee", sortOrder: 1 },
  { id: "juices", name: "العصائر", icon: "cup-soda", sortOrder: 2 },
  { id: "sandwiches", name: "السندوتشات", icon: "sandwich", sortOrder: 3 },
  { id: "brioche", name: "البريوش", icon: "croissant", sortOrder: 4 },
  { id: "crepe", name: "الكريب", icon: "cake-slice", sortOrder: 5 },
  { id: "pancake", name: "البان كيك", icon: "cake-slice", sortOrder: 6 },
  { id: "sweets", name: "الحلو", icon: "cookie", sortOrder: 7 },
];

const newFoods = [
  // 1. المشروبات الساخنة
  {
    id: "hot-1",
    name: "مكياطة",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 3.0,
    rating: 4.9,
    reviewsCount: 140,
    deliveryTime: "5-10 دقيقة",
    calories: 70,
    description: "إسبريسو غني مع رشفة رغوة حليب ناعمة على الطريقة الإيطالية.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["بن مختص", "رغوة حليب"],
  },
  {
    id: "hot-2",
    name: "اسبريسو",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 3.0,
    rating: 4.9,
    reviewsCount: 165,
    deliveryTime: "5-10 دقيقة",
    calories: 10,
    description: "شوت إسبريسو صافي ومكثف بنكهة غنية وإيحاءات متوازنة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["بن إسبريسو مختص فاخر"],
  },
  {
    id: "hot-3",
    name: "مكياطة نص نص",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 4.0,
    rating: 4.8,
    reviewsCount: 95,
    deliveryTime: "5-10 دقيقة",
    calories: 90,
    description: "مزيج متوازن بنسبة متساوية بين الإسبريسو المركز والحليب الساخن.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["إسبريسو", "حليب طازج"],
  },
  {
    id: "hot-4",
    name: "امريكانو",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 3.0,
    rating: 4.8,
    reviewsCount: 110,
    deliveryTime: "5-10 دقيقة",
    calories: 15,
    description: "إسبريسو ممدد بالماء الساخن لقوام خفيف ومذاق قهوة أصيل.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["إسبريسو", "ماء نقي ساخن"],
  },
  {
    id: "hot-5",
    name: "سبيسيال",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 4.0,
    rating: 4.9,
    reviewsCount: 130,
    deliveryTime: "5-10 دقيقة",
    calories: 120,
    description: "خلطة كافي عامر الخاصة من القهوة والحليب بنكهة استثنائية مميزة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["خلطة كافي عامر الخاصة", "حليب فاخر"],
  },
  {
    id: "hot-6",
    name: "نسكافي حليب",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 4.0,
    rating: 4.7,
    reviewsCount: 85,
    deliveryTime: "5-10 دقيقة",
    calories: 110,
    description: "نسكافيه سريع التحضير ممتزج بحليب ساخن طازج ومخملي.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["نسكافيه", "حليب ساخن"],
  },
  {
    id: "hot-7",
    name: "نسكافي بلاك",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 3.0,
    rating: 4.6,
    reviewsCount: 70,
    deliveryTime: "5-10 دقيقة",
    calories: 10,
    description: "نسكافيه أسود بدون إضافات لمذاق كلاسيكي منشط.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["نسكافيه كلاسيك بلاك"],
  },
  {
    id: "hot-8",
    name: "قهوة عربية سادة",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 4.0,
    rating: 4.9,
    reviewsCount: 175,
    deliveryTime: "5-10 دقيقة",
    calories: 5,
    description: "قهوة عربية أصيلة معدة بعناية مع الهيل الفاخر.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["بن عربي محمص", "هيل فاخر"],
  },
  {
    id: "hot-9",
    name: "نسكويك",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 4.0,
    rating: 4.8,
    reviewsCount: 80,
    deliveryTime: "5-10 دقيقة",
    calories: 180,
    description: "مشروب الشوكولاتة اللذيذ بالحليب الساخن للأطفال والكبار.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["شوكولاتة نسكويك", "حليب طازج"],
  },
  {
    id: "hot-10",
    name: "شاي أحمر تونسي نعناع",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 3.0,
    rating: 4.9,
    reviewsCount: 210,
    deliveryTime: "5-10 دقيقة",
    calories: 30,
    description: "شاي أحمر مخدر على الطريقة التونسية بأوراق النعناع الطازجة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["شاي أحمر فاخر", "نعناع أخضر طازج", "سكر حسب الرغبة"],
  },
  {
    id: "hot-11",
    name: "شاي أخضر تونسي نعناع",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 3.0,
    rating: 4.9,
    reviewsCount: 185,
    deliveryTime: "5-10 دقيقة",
    calories: 20,
    description: "شاي أخضر طبيعي منعش مع أوراق النعناع الأخضر الزكية.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["شاي أخضر طبيعي", "نعناع طازج"],
  },
  {
    id: "hot-12",
    name: "كابتشينو إيطالي نوتيلا مكسرات",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 8.0,
    rating: 5.0,
    reviewsCount: 260,
    deliveryTime: "5-10 دقيقة",
    calories: 290,
    description: "كابتشينو إيطالي مخملي مدعم بصوص النوتيلا الغني والمكسرات المقرمشة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["إسبريسو", "حليب مبخر", "نوتيلا أصلية", "مكسرات مشكلة"],
  },
  {
    id: "hot-13",
    name: "كابتشينو إيطالي عادي",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 6.0,
    rating: 4.8,
    reviewsCount: 140,
    deliveryTime: "5-10 دقيقة",
    calories: 160,
    description: "كابتشينو كلاسيكي بطبقة غنية من الفوم الحريري ورشة كاكاو.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["إسبريسو إيطالي", "حليب مبخر", "رغوة حليب"],
  },
  {
    id: "hot-14",
    name: "هوت شوكلت",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 10.0,
    rating: 4.9,
    reviewsCount: 190,
    deliveryTime: "5-10 دقيقة",
    calories: 320,
    description: "شوكولاتة ساخنة غنية وكثيفة محضرة من الشوكولاتة البلجيكية الفاخرة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["شوكولاتة داكنة ذائبة", "حليب طازج", "كريمة"],
  },
  {
    id: "hot-15",
    name: "سنترا حجم صغير",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 6.0,
    rating: 4.7,
    reviewsCount: 65,
    deliveryTime: "5-10 دقيقة",
    calories: 110,
    description: "مشروب سنترا الساخن الخاص بحجم صغير مناسب ولذيذ.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["سنترا", "حليب ساخن"],
  },
  {
    id: "hot-16",
    name: "سنترا حجم وسط",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 8.0,
    rating: 4.8,
    reviewsCount: 85,
    deliveryTime: "5-10 دقيقة",
    calories: 170,
    description: "مشروب سنترا الساخن اللذيذ بحجم وسط مشبع.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["سنترا", "حليب ساخن"],
  },
  {
    id: "hot-17",
    name: "سنترا حجم كبير",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 10.0,
    rating: 4.9,
    reviewsCount: 115,
    deliveryTime: "5-10 دقيقة",
    calories: 230,
    description: "مشروب سنترا الساخن بحجم كبير لعشاق المذاق المميز.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["سنترا", "حليب ساخن"],
  },
  {
    id: "hot-18",
    name: "فرابتشينو",
    categoryId: "hot-drinks",
    categoryName: "المشروبات الساخنة",
    price: 14.0,
    rating: 4.9,
    reviewsCount: 170,
    deliveryTime: "5-10 دقيقة",
    calories: 340,
    description: "مزيج القهوة الغنية مع الكريمة والشوكولاتة الفاخرة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["قهوة إسبريسو", "حليب", "كريمة خفق", "شوكولاتة"],
  },

  // 2. العصائر
  {
    id: "juice-1",
    name: "مانجا",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 7.0,
    rating: 4.9,
    reviewsCount: 150,
    deliveryTime: "5-10 دقيقة",
    calories: 150,
    description: "عصير مانجو طبيعي طازج وبارد بقوام كثيف ومنعش.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["مانجو طبيعي طازج", "ثلج"],
  },
  {
    id: "juice-2",
    name: "جوافة",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 6.0,
    rating: 4.7,
    reviewsCount: 80,
    deliveryTime: "5-10 دقيقة",
    calories: 120,
    description: "عصير جوافة طبيعي منعش بنكهة غنية وفيتامينات طبيعية.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["جوافة طازجة", "ثلج"],
  },
  {
    id: "juice-3",
    name: "فراولة",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 5.0,
    rating: 4.8,
    reviewsCount: 120,
    deliveryTime: "5-10 دقيقة",
    calories: 110,
    description: "عصير فراولة طبيعي طازج بلمسة انتعاش مثالية.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["فراولة طازجة", "ثلج"],
  },
  {
    id: "juice-4",
    name: "فروبي مانجا مكسرات",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 8.0,
    rating: 5.0,
    reviewsCount: 210,
    deliveryTime: "5-10 دقيقة",
    calories: 280,
    description: "فروبي مانجو سموثي مثلج وكثيف ومزين بالمكسرات المحمصة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["مانجو مجمد", "حليب", "مكسرات مشكلة"],
  },
  {
    id: "juice-5",
    name: "فروبي فراولة",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 7.0,
    rating: 4.9,
    reviewsCount: 160,
    deliveryTime: "5-10 دقيقة",
    calories: 220,
    description: "سموثي فروبي فراولة مثلج بنكهة كريمية لا تقاوم.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["فراولة مثلجة", "حليب", "ثلج مجروش"],
  },
  {
    id: "juice-6",
    name: "أفوكادو",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 10.0,
    rating: 4.8,
    reviewsCount: 110,
    deliveryTime: "5-10 دقيقة",
    calories: 260,
    description: "عصير أفوكادو كريمي طازج ومغذي ومعد بالطلب.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["أفوكادو طازج", "حليب", "عسل خفيف"],
  },
  {
    id: "juice-7",
    name: "أفوكادو عسل مكسرات",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 15.0,
    rating: 5.0,
    reviewsCount: 240,
    deliveryTime: "5-10 دقيقة",
    calories: 380,
    description: "أفوكادو طبيعي فاخر مع العسل الصافي وطبقة وفيرة من المكسرات.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["أفوكادو طازج", "عسل نحل طبيعي", "مكسرات مشكلة فاخرة", "حليب"],
  },
  {
    id: "juice-8",
    name: "ميلك شيك (لوتس + نوتيلا + بستاشيو) حجم L",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 15.0,
    rating: 5.0,
    reviewsCount: 290,
    deliveryTime: "5-10 دقيقة",
    calories: 450,
    description: "ميلك شيك ثلاثي النكهات الخارق بمزيج اللوتس والنوتيلا والبستاشيو حجم L.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["آيس كريم", "لوتس", "نوتيلا", "بستاشيو إيطالي", "حليب"],
  },
  {
    id: "juice-9",
    name: "ميلك شيك (لوتس + نوتيلا + بستاشيو) حجم XL",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 17.0,
    rating: 5.0,
    reviewsCount: 320,
    deliveryTime: "5-10 دقيقة",
    calories: 550,
    description: "الحجم الملكي XL من ميلك شيك اللوتس والنوتيلا والبستاشيو مع الكريمة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["آيس كريم مضاعف", "لوتس", "نوتيلا", "بستاشيو", "كريمة خفق"],
  },
  {
    id: "juice-10",
    name: "آيس كوفي",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 12.0,
    rating: 4.9,
    reviewsCount: 195,
    deliveryTime: "5-10 دقيقة",
    calories: 140,
    description: "قهوة مثلجة منعشة محضرة من بن عامر المختص مع الثلج والحليب.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["إسبريسو مختص", "حليب بارد", "ثلج"],
  },
  {
    id: "juice-11",
    name: "آيس سبانش لاتيه",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 12.0,
    rating: 5.0,
    reviewsCount: 380,
    deliveryTime: "5-10 دقيقة",
    calories: 230,
    description: "سبانش لاتيه بارد ومحلى بالحليب المكثف بنكهة لا تقاوم.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["إسبريسو دبل", "حليب مكثف", "حليب بارد", "ثلج"],
  },
  {
    id: "juice-12",
    name: "موخيتو",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 12.0,
    rating: 4.9,
    reviewsCount: 220,
    deliveryTime: "5-10 دقيقة",
    calories: 130,
    description: "موهيتو منعش ومثلج بالليمون والنعناع والصودا الفوارة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["ليمون طازج", "نعناع أخضر", "صودا", "سيروب نكهات"],
  },
  {
    id: "juice-13",
    name: "آيس أمريكانو",
    categoryId: "juices",
    categoryName: "العصائر",
    price: 12.0,
    rating: 4.8,
    reviewsCount: 130,
    deliveryTime: "5-10 دقيقة",
    calories: 15,
    description: "إسبريسو صافي على الثلج والماء البارد لعشاق الانتعاش الكلاسيكي.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["إسبريسو دبل", "ماء بارد", "ثلج مكعبات"],
  },

  // 3. السندوتشات
  {
    id: "sand-1",
    name: "مفروم وطني",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 4.0,
    rating: 4.9,
    reviewsCount: 230,
    deliveryTime: "10-15 دقيقة",
    calories: 340,
    description: "سندوتش لحم مفروم وطني متبل ببهارات ليبية شهية وخبز طازج.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["لحم مفروم وطني", "خبز طازج", "بهارات"],
  },
  {
    id: "sand-2",
    name: "مفروم دحي",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 5.0,
    rating: 5.0,
    reviewsCount: 270,
    deliveryTime: "10-15 دقيقة",
    calories: 420,
    description: "مفروم وطني شهي مع بيض مقلي طازج على الصاج.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["لحم مفروم وطني", "بيض (دحي)", "خبز طازج"],
  },
  {
    id: "sand-3",
    name: "تن",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 3.0,
    rating: 4.8,
    reviewsCount: 160,
    deliveryTime: "10-15 دقيقة",
    calories: 290,
    description: "سندوتش تن فاخر مع الزيتون والصلصة اللذيذة.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["تونة فاخرة", "زيتون", "خبز طازج"],
  },
  {
    id: "sand-4",
    name: "تن دحي",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 4.0,
    rating: 4.9,
    reviewsCount: 210,
    deliveryTime: "10-15 دقيقة",
    calories: 370,
    description: "المزيج الكلاسيكي المفضل من التونة والبيض المطبوخ بالخبز الطازج.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["تونة", "بيض (دحي)", "خبز ساخن"],
  },
  {
    id: "sand-5",
    name: "دحي جبنة",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 4.0,
    rating: 4.8,
    reviewsCount: 140,
    deliveryTime: "10-15 دقيقة",
    calories: 310,
    description: "بيض مطبوخ ساخن مع جبنة ذائبة شهية.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["بيض (دحي)", "جبنة ذائبة", "خبز"],
  },
  {
    id: "sand-6",
    name: "كبدة وطني",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 13.0,
    rating: 5.0,
    reviewsCount: 310,
    deliveryTime: "10-15 دقيقة",
    calories: 380,
    description: "كبدة خروف وطنية طازجة ومتبلة ومطبوخة على أصولها.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["كبدة وطني طازجة", "تتبيلة خاصة", "فلفل وليمون"],
  },
  {
    id: "sand-7",
    name: "قلايا لحم وطني",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 10.0,
    rating: 5.0,
    reviewsCount: 290,
    deliveryTime: "10-15 دقيقة",
    calories: 410,
    description: "قلايا لحم وطني بلدي ناعم ومقرمش بنكهة ليبية أصيلة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["لحم وطني مقلي", "تتبيلة بهارات", "خبز سخن"],
  },
  {
    id: "sand-8",
    name: "كبدة دجاج",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 7.0,
    rating: 4.8,
    reviewsCount: 150,
    deliveryTime: "10-15 دقيقة",
    calories: 320,
    description: "كبدة دجاج طرية ومتبلة بالبصل والبهارات الخاصة.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["كبدة دجاج", "بصل", "بهارات وتوابل"],
  },
  {
    id: "sand-9",
    name: "إضافة جبنة",
    categoryId: "sandwiches",
    categoryName: "السندوتشات",
    price: 1.0,
    rating: 4.9,
    reviewsCount: 180,
    deliveryTime: "فوري",
    calories: 80,
    description: "شريحة جبنة إضافية ذائبة لأي سندوتش من اختيارك.",
    image: "/images/logo.png",
    isPopular: false,
    ingredients: ["شريحة جبنة ذائبة"],
  },

  // 4. البريوش
  {
    id: "brioche-1",
    name: "بريوش نوتيلا مكسرات",
    categoryId: "brioche",
    categoryName: "البريوش",
    price: 10.0,
    rating: 5.0,
    reviewsCount: 270,
    deliveryTime: "5-10 دقيقة",
    calories: 390,
    description: "خبز بريوش فرنسي هش وطري محشو بطبقة غنية من النوتيلا والمكسرات.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["خبز بريوش بالزبدة", "نوتيلا أصلية", "مكسرات مقرمشة"],
  },
  {
    id: "brioche-2",
    name: "بريوش جبنة عسل وزعتر",
    categoryId: "brioche",
    categoryName: "البريوش",
    price: 10.0,
    rating: 4.9,
    reviewsCount: 190,
    deliveryTime: "5-10 دقيقة",
    calories: 340,
    description: "مزيج متناغم وفاخر بين الجبنة الكريمية والعسل الطبيعي ورشة الزعتر.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["خبز بريوش طازج", "جبنة كريمية", "عسل نحل", "زعتر بلدي"],
  },

  // 5. الكريب
  {
    id: "crepe-1",
    name: "كريب رول",
    categoryId: "crepe",
    categoryName: "الكريب",
    price: 20.0,
    rating: 4.9,
    reviewsCount: 180,
    deliveryTime: "10-15 دقيقة",
    calories: 420,
    description: "كريب رول مقرمش محشو بالكريمة والشوكولاتة ومقطع لقطع أنيقة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["عجينة كريب فرنسية", "شوكولاتة", "مكسرات"],
  },
  {
    id: "crepe-2",
    name: "كريب كلاسيك نوتيلا",
    categoryId: "crepe",
    categoryName: "الكريب",
    price: 25.0,
    rating: 5.0,
    reviewsCount: 230,
    deliveryTime: "10-15 دقيقة",
    calories: 480,
    description: "الكريب الكلاسيكي الذهبي المغطى بسخاء بشوكولاتة النوتيلا الذائبة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["كريب ذهبي طازج", "شوكولاتة نوتيلا أصلية"],
  },
  {
    id: "crepe-3",
    name: "كريب مكس",
    categoryId: "crepe",
    categoryName: "الكريب",
    price: 25.0,
    rating: 5.0,
    reviewsCount: 260,
    deliveryTime: "10-15 دقيقة",
    calories: 520,
    description: "كريب مكس بصوصات متعددة (نوتيلا + لوتس + شوكولاتة بيضاء).",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["كريب طازج", "نوتيلا", "لوتس", "شوكولاتة بيضاء"],
  },
  {
    id: "crepe-4",
    name: "كريب تام فواكه",
    categoryId: "crepe",
    categoryName: "الكريب",
    price: 35.0,
    rating: 5.0,
    reviewsCount: 310,
    deliveryTime: "10-15 دقيقة",
    calories: 590,
    description: "كريب فاخر محشو ومزين بتشكيلة واسعة من الفواكه الطازجة والشوكولاتة الفاخرة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["كريب", "فراولة", "موز", "كيوي", "نوتيلا", "مكسرات"],
  },

  // 6. البان كيك
  {
    id: "pancake-1",
    name: "بان كيك نوتيلا مكسرات",
    categoryId: "pancake",
    categoryName: "البان كيك",
    price: 20.0,
    rating: 4.9,
    reviewsCount: 220,
    deliveryTime: "10-15 دقيقة",
    calories: 450,
    description: "طبقات بان كيك أمريكية هشة ومغطاة بالنوتيلا والمكسرات المحمصة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["بان كيك هش", "نوتيلا", "مكسرات مشكلة"],
  },
  {
    id: "pancake-2",
    name: "بان كيك نوتيلا مكسرات فواكه",
    categoryId: "pancake",
    categoryName: "البان كيك",
    price: 30.0,
    rating: 5.0,
    reviewsCount: 280,
    deliveryTime: "10-15 دقيقة",
    calories: 540,
    description: "بان كيك ممتلئ بالنوتيلا والمكسرات وقطع الفراولة والموز الطازجة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["بان كيك أمريكي", "نوتيلا", "مكسرات", "فراولة وموز"],
  },
  {
    id: "pancake-3",
    name: "وافل اختراع تام",
    categoryId: "pancake",
    categoryName: "البان كيك",
    price: 30.0,
    rating: 5.0,
    reviewsCount: 340,
    deliveryTime: "10-15 دقيقة",
    calories: 580,
    description: "وافل بلجيكي مقرمش ومزين بابتكار عامر الخاص مع الآيس كريم والخلطات المميزة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["وافل بلجيكي مقرمش", "شوكولاتات مشكلة", "آيس كريم", "مكسرات"],
  },

  // 7. الحلو
  {
    id: "sweet-1",
    name: "تيراميسو",
    categoryId: "sweets",
    categoryName: "الحلو",
    price: 10.0,
    rating: 5.0,
    reviewsCount: 290,
    deliveryTime: "فوري",
    calories: 320,
    description: "حلوى التيراميسو الإيطالية الكلاسيكية ببسكويت ليدي فينجر المغموس بالقهوة والكريمة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["جبنة ماسكاربوني", "إسبريسو", "بسكويت أصابع", "بودرة كاكاو"],
  },
  {
    id: "sweet-2",
    name: "بسبوسة بالقشطة",
    categoryId: "sweets",
    categoryName: "الحلو",
    price: 6.0,
    rating: 4.9,
    reviewsCount: 210,
    deliveryTime: "فوري",
    calories: 310,
    description: "بسبوسة ذهبية طرية محشوة بالقشطة البلدية الطازجة والقطر المتوازن.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["سميد فاخر", "قشطة طازجة", "شيرة سمن بلدي"],
  },
  {
    id: "sweet-3",
    name: "بسبوسة جلاكسي",
    categoryId: "sweets",
    categoryName: "الحلو",
    price: 6.0,
    rating: 4.9,
    reviewsCount: 240,
    deliveryTime: "فوري",
    calories: 350,
    description: "بسبوسة مميزة مغطاة بطبقة غنية من شوكولاتة جلاكسي الحريرية.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["بسبوسة طازجة", "شوكولاتة جلاكسي ناعمة"],
  },
  {
    id: "sweet-4",
    name: "كوكيز نوتيلا",
    categoryId: "sweets",
    categoryName: "الحلو",
    price: 8.0,
    rating: 5.0,
    reviewsCount: 280,
    deliveryTime: "فوري",
    calories: 270,
    description: "كوكيز ساخن ومقرمش من الأطراف وطري من الداخل محشو بنوتيلا ذائبة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["عجينة كوكيز بالزبدة", "حشوة نوتيلا ذائبة"],
  },
  {
    id: "sweet-5",
    name: "كوكيز دبل بستاشيو",
    categoryId: "sweets",
    categoryName: "الحلو",
    price: 10.0,
    rating: 5.0,
    reviewsCount: 310,
    deliveryTime: "فوري",
    calories: 320,
    description: "كوكيز فاخر بحشوة مضاعفة من زبدة الفستق الحلبي وقطع البستاشيو المحمصة.",
    image: "/images/logo.png",
    isPopular: true,
    ingredients: ["كوكيز زبدة", "كريمة بستاشيو إيطالية", "فستق حلبي محمص"],
  },
];

async function run() {
  console.log("Connecting to PostgreSQL...");
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    console.log("1. Cleaning old foods and categories...");
    await client.query("DELETE FROM foods;");
    await client.query("DELETE FROM categories;");

    console.log("2. Inserting new categories...");
    for (const cat of newCategories) {
      await client.query(
        `INSERT INTO categories (id, name, icon, item_count, sort_order)
         VALUES ($1, $2, $3, $4, $5)`,
        [cat.id, cat.name, cat.icon, 0, cat.sortOrder]
      );
    }

    console.log(`3. Inserting ${newFoods.length} new foods...`);
    for (const food of newFoods) {
      await client.query(
        `INSERT INTO foods (
          id, name, category_id, category_name, price, rating, reviews_count,
          delivery_time, calories, description, image, is_popular, ingredients
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`,
        [
          food.id,
          food.name,
          food.categoryId,
          food.categoryName,
          food.price,
          food.rating,
          food.reviewsCount,
          food.deliveryTime,
          food.calories,
          food.description,
          food.image,
          food.isPopular,
          JSON.stringify(food.ingredients),
        ]
      );
    }

    console.log("4. Updating categories item counts...");
    for (const cat of newCategories) {
      await client.query(
        `UPDATE categories
         SET item_count = (SELECT COUNT(*) FROM foods WHERE category_id = $1)
         WHERE id = $1`,
        [cat.id]
      );
    }

    console.log("5. Updating banners category IDs to new categories...");
    await client.query(
      `UPDATE banners SET category_id = 'hot-drinks' WHERE category_id NOT IN ('hot-drinks', 'juices', 'sandwiches', 'brioche', 'crepe', 'pancake', 'sweets')`
    );

    await client.query("COMMIT");
    console.log("🎉 Successfully replaced all categories and items in the database!");
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("❌ Error replacing menu in database:", err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

run();
